// <auto-generated />
namespace Day_10_Project_ASP.NET_IV._1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MadeTitleDirectorNonNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MadeTitleDirectorNonNull));
        
        string IMigrationMetadata.Id
        {
            get { return "201507211413182_MadeTitleDirectorNonNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
